(asdf:defsystem #:cl-claw-tests
  :description "Tests for cl-claw"
  :author "Chrysolambda"
  :license "MIT"
  :depends-on (#:cl-claw #:fiveam)
  :components ((:module "tests/cl-adapted/src/infra"
                :components
                ((:file "binaries.test")
                 (:file "retry.test")
                 (:file "abort-signal.test")
                 (:file "env.test")
                 (:file "channel-activity.test")
                 (:file "dedupe.test")
                 (:file "diagnostic-events.test")
                 (:file "fiveam-restart.test")
                 (:file "fiveam-retry-policy.test")
                 (:file "fiveam-state-migrations.test")
                 (:file "fiveam-tailnet.test")
                 (:file "fiveam-voicewake.test")
                 (:file "fiveam-fs-safe.test")
                 (:file "fiveam-net.test"))))
  :perform (asdf:test-op (op c)
             (flet ((run-suite (suite-sym pkg-name)
                      (let ((suite (find-symbol (string-upcase suite-sym)
                                                (find-package pkg-name))))
                        (when suite
                          (symbol-call :fiveam :run! suite)))))
               (run-suite "binaries-suite" :cl-claw.infra.binaries.test)
               (run-suite "retry-suite" :cl-claw.infra.retry.test)
               (run-suite "abort-signal-suite" :cl-claw.infra.abort-signal.test)
               (run-suite "env-suite" :cl-claw.infra.env.test)
               (run-suite "channel-activity-suite" :cl-claw.infra.channel-activity.test)
               (run-suite "dedupe-suite" :cl-claw.infra.dedupe.test)
               (run-suite "diagnostic-events-suite" :cl-claw.infra.diagnostic-events.test)
               (run-suite "restart-suite" :cl-claw.infra.restart.test)
               (run-suite "retry-policy-suite" :cl-claw.infra.retry-policy.test)
               (run-suite "state-migrations-suite" :cl-claw.infra.state-migrations.test)
               (run-suite "tailnet-suite" :cl-claw.infra.tailnet.test)
               (run-suite "voicewake-suite" :cl-claw.infra.voicewake.test)
               (run-suite "fs-safe-suite" :cl-claw.infra.fs-safe.test)
               (run-suite "net-suite" :cl-claw.infra.net.test))))
