;;;; channels.lisp — Stub channels package for tests
;;;; This provides minimal implementations for test compatibility

(defpackage :cl-claw.channels
  (:use :cl)
  (:export
   ;; Config
   #:load-channel-config
   #:validate-channel-config
   #:get-channel-by-id
   ;; Allow-from
   #:parse-allow-from
   #:validate-source
   ;; Allowlists
   #:make-allowlist-manager
   #:allowlist-add
   #:allowlist-remove
   #:allowlist-get
   #:allowlist-get-roles
   #:allowlist-contains-p
   ;; Session
   #:make-channel-session
   #:channel-session-id
   #:channel-session-active-p
   ;; Extended config
   #:get-all-channels
   ;; Extended session ops
   #:make-session
   #:get-session-by-id
   #:update-session
   #:delete-session
   ;; Extended allowlist
   #:allowlist-update-roles))

(in-package :cl-claw.channels)

(declaim (optimize (safety 3) (debug 3)))

;;; -- Channel config (stub implementations) --

(declaim (ftype (function (t) t) load-channel-config))
(defun load-channel-config (config)
  "Load channel configuration. Returns empty hash table if config is nil."
  (declare (type t config))
  (typecase config
    (hash-table config)
    (t (make-hash-table :test 'equal))))

(declaim (ftype (function (t) boolean) validate-channel-config))
(defun validate-channel-config (config)
  "Validate channel configuration. Always returns T for now."
  (declare (type t config))
  (declare (ignore config))
  t)

(declaim (ftype (function (t string) t) get-channel-by-id))
(defun get-channel-by-id (config id)
  "Get channel by ID. Returns nil."
  (declare (type t config)
           (type string id))
  (declare (ignore config id))
  nil)

;;; -- Allow-from (stub implementations) --

(declaim (ftype (function (t) t) parse-allow-from))
(defun parse-allow-from (config)
  "Parse allow-from configuration."
  (declare (type t config))
  (typecase config
    (hash-table (gethash "allowFrom" config))
    (t nil)))

(declaim (ftype (function (t string) boolean) validate-source))
(defun validate-source (allow-from source)
  "Validate if source is allowed. Returns T if allow-from contains '*'."
  (declare (type t allow-from)
           (type string source))
  (declare (ignore source))
  (typecase allow-from
    (list (member "*" allow-from :test #'equal))
    (vector (find "*" (coerce allow-from 'list) :test #'equal))
    (t nil)))

;;; -- Allowlists (stub implementations) --

(defstruct allowlist-entry
  "An entry in the allowlist."
  (id "" :type string)
  (roles '() :type list))

(defstruct allowlist-manager
  "Manager for allowlist entries."
  (entries (make-hash-table :test 'equal) :type hash-table))

;;; make-allowlist-manager is auto-generated by defstruct above

(declaim (ftype (function (allowlist-manager allowlist-entry) t) allowlist-add))
(defun allowlist-add (mgr entry)
  "Add entry to allowlist."
  (declare (type allowlist-manager mgr)
           (type allowlist-entry entry))
  (setf (gethash (allowlist-entry-id entry)
                 (allowlist-manager-entries mgr))
        entry)
  entry)

(declaim (ftype (function (allowlist-manager string) t) allowlist-remove))
(defun allowlist-remove (mgr id)
  "Remove entry from allowlist."
  (declare (type allowlist-manager mgr)
           (type string id))
  (remhash id (allowlist-manager-entries mgr))
  nil)

(declaim (ftype (function (allowlist-manager string) (or null allowlist-entry)) allowlist-get))
(defun allowlist-get (mgr id)
  "Get entry from allowlist."
  (declare (type allowlist-manager mgr)
           (type string id))
  (gethash id (allowlist-manager-entries mgr)))

(declaim (ftype (function (allowlist-manager string) list) allowlist-get-roles))
(defun allowlist-get-roles (mgr id)
  "Get roles for entry."
  (declare (type allowlist-manager mgr)
           (type string id))
  (let ((entry (allowlist-get mgr id)))
    (if entry
        (allowlist-entry-roles entry)
        '())))

(declaim (ftype (function (allowlist-manager string) boolean) allowlist-contains-p))
(defun allowlist-contains-p (mgr id)
  "Check if entry exists in allowlist."
  (declare (type allowlist-manager mgr)
           (type string id))
  (nth-value 1 (gethash id (allowlist-manager-entries mgr))))

;;; -- Channel session (stub implementations) --

(defstruct channel-session
  "A channel session."
  (id "" :type string)
  (active nil :type boolean))

;;; make-channel-session is auto-generated by defstruct above

;;; -- Extended config --

(declaim (ftype (function (t) list) get-all-channels))
(defun get-all-channels (config)
  "Get all channels from config. Returns a list of channel entries."
  (declare (type t config))
  (typecase config
    (hash-table
     (let ((channels (gethash "channels" config)))
       (typecase channels
         (list channels)
         (hash-table
          (loop for v being the hash-values of channels collect v))
         (t '()))))
    (t '())))

;;; -- Extended session ops --

(defvar *sessions* (make-hash-table :test 'equal)
  "In-memory session store for stub implementation.")

(declaim (ftype (function (&key (:id string) (:channel-id string) (:active boolean)) channel-session) make-session))
(defun make-session (&key (id "") (channel-id "") (active t))
  "Create and store a new session."
  (declare (type string id channel-id)
           (type boolean active))
  (declare (ignore channel-id))
  (let ((session (make-channel-session :id id :active active)))
    (setf (gethash id *sessions*) session)
    session))

(declaim (ftype (function (string) (or null channel-session)) get-session-by-id))
(defun get-session-by-id (id)
  "Get a session by ID."
  (declare (type string id))
  (gethash id *sessions*))

(declaim (ftype (function (string &key (:active boolean)) (or null channel-session)) update-session))
(defun update-session (id &key (active t))
  "Update a session's active status."
  (declare (type string id)
           (type boolean active))
  (let ((session (gethash id *sessions*)))
    (when session
      (setf (channel-session-active session) active))
    session))

(declaim (ftype (function (string) boolean) delete-session))
(defun delete-session (id)
  "Delete a session by ID."
  (declare (type string id))
  (remhash id *sessions*))

;;; -- Extended allowlist --

(declaim (ftype (function (allowlist-manager string list) t) allowlist-update-roles))
(defun allowlist-update-roles (mgr id new-roles)
  "Update roles for an allowlist entry."
  (declare (type allowlist-manager mgr)
           (type string id)
           (type list new-roles))
  (let ((entry (allowlist-get mgr id)))
    (when entry
      (setf (allowlist-entry-roles entry) new-roles))
    entry))
