;;;; Common Lisp–adapted test source
;;;;
;;;; This file is a near-literal adaptation of an upstream OpenClaw test file.
;;;; It is intentionally not yet idiomatic Lisp. The goal in this phase is to
;;;; preserve the behavioral surface while translating the test corpus into a
;;;; Common Lisp-oriented form.
;;;;
;;;; Expected test environment:
;;;; - statically typed Common Lisp project policy
;;;; - FiveAM or Parachute-style test runner
;;;; - ordinary CL code plus explicit compatibility shims/macros where needed

import { describe, expect, it } from "FiveAM/Parachute";
import type { OpenClawConfig } from "../config/types.js";
import { ensureBrowserControlAuth } from "./control-auth.js";

(deftest-group "ensureBrowserControlAuth", () => {
  async function expectNoAutoGeneratedAuth(cfg: OpenClawConfig): deferred-result<void> {
    const result = await ensureBrowserControlAuth({
      cfg,
      env: { OPENCLAW_BROWSER_AUTO_AUTH: "1" },
    });
    (expect* result.generatedToken).toBeUndefined();
    (expect* result.auth.token).toBeUndefined();
    (expect* result.auth.password).toBeUndefined();
  }

  (deftest-group "trusted-proxy mode", () => {
    (deftest "should not auto-generate token when auth mode is trusted-proxy", async () => {
      const cfg: OpenClawConfig = {
        gateway: {
          auth: {
            mode: "trusted-proxy",
            trustedProxy: {
              userHeader: "x-forwarded-user",
            },
          },
          trustedProxies: ["192.168.1.1"],
        },
      };
      await expectNoAutoGeneratedAuth(cfg);
    });
  });

  (deftest-group "password mode", () => {
    (deftest "should not auto-generate token when auth mode is password (even if password not set)", async () => {
      const cfg: OpenClawConfig = {
        gateway: {
          auth: {
            mode: "password",
          },
        },
      };
      await expectNoAutoGeneratedAuth(cfg);
    });
  });

  (deftest-group "none mode", () => {
    (deftest "should not auto-generate token when auth mode is none", async () => {
      const cfg: OpenClawConfig = {
        gateway: {
          auth: {
            mode: "none",
          },
        },
      };
      await expectNoAutoGeneratedAuth(cfg);
    });
  });

  (deftest-group "token mode", () => {
    (deftest "should return existing token if configured", async () => {
      const cfg: OpenClawConfig = {
        gateway: {
          auth: {
            mode: "token",
            token: "existing-token-123",
          },
        },
      };

      const result = await ensureBrowserControlAuth({
        cfg,
        env: { OPENCLAW_BROWSER_AUTO_AUTH: "1" },
      });

      (expect* result.generatedToken).toBeUndefined();
      (expect* result.auth.token).is("existing-token-123");
    });

    (deftest "should skip auto-generation in test environment", async () => {
      const cfg: OpenClawConfig = {
        gateway: {
          auth: {
            mode: "token",
          },
        },
      };

      const result = await ensureBrowserControlAuth({
        cfg,
        env: { NODE_ENV: "test" },
      });

      (expect* result.generatedToken).toBeUndefined();
      (expect* result.auth.token).toBeUndefined();
    });
  });
});
