;;;; apply-patch.lisp — Safe patch-style file operations

(defpackage :cl-claw.agents.apply-patch
  (:use :cl)
  (:export
   :apply-patch))

(in-package :cl-claw.agents.apply-patch)

(declaim (optimize (safety 3) (debug 3)))

(declaim (ftype (function (string) string) %trim))
(defun %trim (value)
  (declare (type string value))
  (string-trim '(#\Space #\Tab #\Newline #\Return) value))

(declaim (ftype (function (string) boolean) %absolute-path-p))
(defun %absolute-path-p (path)
  (declare (type string path))
  (let ((len (length path)))
    (declare (type fixnum len))
    (or (and (> len 0) (char= (char path 0) #\/))
        (and (> len 2)
             (alpha-char-p (char path 0))
             (char= (char path 1) #\:)))))

(declaim (ftype (function (string) boolean) %contains-parent-ref-p))
(defun %contains-parent-ref-p (path)
  (declare (type string path))
  (let ((parts (uiop:split-string path :separator '(#\/ #\\))))
    (declare (type list parts))
    (loop for part in parts
          thereis (string= part ".."))))

(declaim (ftype (function (string string &key (:workspace-only boolean)) string)
                resolve-patch-path))
(defun resolve-patch-path (cwd path &key (workspace-only t))
  (declare (type string cwd path)
           (type boolean workspace-only))
  (let* ((root (namestring (uiop:ensure-directory-pathname (truename cwd))))
         (trimmed (%trim path)))
    (declare (type string root trimmed))
    (when (and workspace-only
               (not (%absolute-path-p trimmed))
               (%contains-parent-ref-p trimmed))
      (error "Path escapes workspace: ~a" path))
    (let* ((candidate (if (%absolute-path-p trimmed)
                          (uiop:ensure-pathname trimmed)
                          (merge-pathnames trimmed (uiop:ensure-directory-pathname root))))
           (resolved (namestring (uiop:ensure-pathname candidate))))
      (declare (type string resolved))
      (when (and workspace-only
                 (not (or (string= resolved root)
                          (uiop:string-prefix-p root resolved))))
        (error "Path escapes workspace: ~a" path))
      resolved)))

(declaim (ftype (function (string) null) ensure-parent-directory))
(defun ensure-parent-directory (path)
  (declare (type string path))
  (uiop:ensure-all-directories-exist (list path))
  nil)

(declaim (ftype (function (list string &key (:workspace-only boolean)) list) apply-patch))
(defun apply-patch (operations cwd &key (workspace-only t))
  (declare (type list operations)
           (type string cwd)
           (type boolean workspace-only))
  (let ((changed nil))
    (declare (type list changed))
    (dolist (op operations)
      (unless (hash-table-p op)
        (error "Patch operation must be a hash-table"))
      (let* ((kind-raw (gethash "type" op ""))
             (kind (string-downcase (if (stringp kind-raw) kind-raw (format nil "~a" kind-raw)))))
        (declare (type t kind-raw)
                 (type string kind))
        (cond
          ((or (string= kind "add") (string= kind "update"))
           (let* ((path (resolve-patch-path cwd (format nil "~a" (gethash "path" op ""))
                                            :workspace-only workspace-only))
                  (content (format nil "~a" (gethash "content" op ""))))
             (declare (type string path content))
             (ensure-parent-directory path)
             (with-open-file (out path :direction :output :if-exists :supersede :if-does-not-exist :create)
               (write-string content out))
             (push path changed)))
          ((string= kind "delete")
           (let ((path (resolve-patch-path cwd (format nil "~a" (gethash "path" op ""))
                                           :workspace-only workspace-only)))
             (declare (type string path))
             (when (probe-file path)
               (delete-file path)
               (push path changed))))
          ((string= kind "move")
           (let* ((from (resolve-patch-path cwd (format nil "~a" (gethash "path" op ""))
                                            :workspace-only workspace-only))
                  (to (resolve-patch-path cwd (format nil "~a" (gethash "to" op ""))
                                          :workspace-only workspace-only)))
             (declare (type string from to))
             (ensure-parent-directory to)
             (rename-file from to)
             (push to changed)))
          (t
           (error "Unsupported patch operation type: ~a" kind)))))
    (nreverse changed)))
